cartApi created
wecode-bootcamp-korea/justcode-5-1st-codeisneverthat-back pull request #14
Opened 2022-06-27 01:21 UTC by nadia506

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)

- [ ] 레이아웃 구현
- [ ] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)

- cart API 구현 

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)

cart api get 와 post 를 구현했습니다. 
<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)

- layered patter 과 sql 문을 더 배울 수 있었습니다. 
<br />

## :: 기타 질문 및 특이 사항

- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시)

2022-06-27 03:35 UTC, thenoondaydream commented on models/cart.js
> +     `;
쿼리문 명령을 실행해보면, 테이블상에서 같은 프로덕트가 url만큼 중복되어서 출력됩니다. 이 부분 확인 부탁드려요  ☺️

2022-06-27 03:42 UTC, thenoondaydream requested changes

2022-06-27 03:42 UTC, thenoondaydream commented on models/cart.js
> +    const {user_id, product_details_id, quantity} = addItemDto;
Front-end쪽에서 requst를 보낼 때, user_id를 어떻게 보낼 수 있을지 다같이 한번 고민해봐야할 것 같아요!!

2022-06-27 03:42 UTC, thenoondaydream commented on models/cart.js
> +     `;
쿼리문 명령을 실행해보면, 테이블상에서 같은 프로덕트가 url만큼 중복되어서 출력됩니다. 이 부분 확인 부탁드려요 ☺️

2022-06-27 03:42 UTC, thenoondaydream commented on services/cart.js
> +// }
getCartItem은 models쪽으로 옮기신거죠~?

2022-06-28 01:52 UTC, thenoondaydream commented on models/cart.js
> +    WHERE MOD(product_images.id,2) = 0
<img width="1287" alt="스크린샷 2022-06-28 오전 10 52 06" src="https://user-images.githubusercontent.com/104835917/176070244-a4acce46-60ec-458b-9533-7dbfe8e62068.png">
이 부분 오류가 나는거 같은데 같이 한번 확인해볼 수 있을까요~?

2022-06-28 01:53 UTC, thenoondaydream commented on models/cart.js
> +    WHERE MOD(product_images.id,2) = 0
<img width="1065" alt="스크린샷 2022-06-28 오전 10 53 15" src="https://user-images.githubusercontent.com/104835917/176070491-e66e111d-671a-42eb-a450-2d08a8021f21.png">

2022-06-29 02:06 UTC, ssujinc approved these changes

2022-06-29 02:06 UTC, thenoondaydream approved these changes

2022-06-29 02:06 UTC, leejulie09 approved these changes

2022-06-29 02:06 UTC, merged